name: asap
generic:
  seed: 42
  log_dir: './log/'
  clear_log: True
data:
  dataset_path: "data/asap/dataset"
  metadata_path: "data/asap/dataset/metadata.csv"
  new_tokens_dir: "data/asap/vocab"
  dataset_save_path: "data/asap/dataset/dataset.csv"
  max_example_len: 8500
  shuffle: True
  dataset_split: [.8, .1, .1]
  batch_size: 1
training:
  epochs: 500000
  save: True
  save_every: 20
  save_dir: "./saved_models/"
  load: False
  decode: True
  decode_every: 10
  decode_dir: "./decoded/"
eval:
  load_path: "./saved_models/model_epoch_580.pt"
transformer:  # [1027, 130, 3, 131, 131, 36, 257, 52]
  embedding_sizes: [1027, 131, 4, 131, 131, 36, 257, 52]  # TODO remove instrument, since all piano
  d_model: 512
  n_head: 8
  max_len: 8500
  ffn_hidden: 2048  # 2048
  drop_prob: 0.1
  n_layers: 6 # 6
  lr: 1e-5
  bayes_compression: True