name: asap
generic:
  seed: 42
  log_dir: './log/'
  clear_log: True
data:
  dataset_path: "data/asap/dataset"
  csv_path: "data/asap/dataset/metadata.csv"
  new_tokens_dir: "data/asap/vocab"
  dataset_save_path: "data/asap/dataset/dataset.csv"
  max_example_len: 25000
  shuffle: True
  dataset_split: [.8, .1, .1]
  batch_size: 4
encoder:
  input_size: 512
  hidden_size: 512
  lr: 1e-4
decoder:
  hidden_size: 512
  lr: 1e-4
training:
  epochs: 1
  save: True
  save_every_x_epochs: 1
  save_dir: "./models/"